### ISSUE TITLE
v3.3.21 failed to switch proxies on Firefox

### ISSUE THREAD

**Issue by Uuzics** [zero-peak/ZeroOmega#108]
ZeroOmega 3.3.21
Firefox 128.7.0esr (64bit)
Windows 10 22H2 (19045.5487)

Unable to switch to any proxy with 3.3.21, the UI shows a proxy has been applied but it's actually in Direct mode.

Downgrading to 3.3.20 sovles the problem.

How to reproduce:
- Fresh installation of Firefox (I've tested several ESR installations, such as 128.7, 128.6, none of them works with v3.3.21)
- Install ZeroOmega 3.3.21
- Config proxies
- Test if switching proxies works

Is there any information I can provide to help with debugging?

**Comment by gweaver2077** [comment]
I also encountered this problem on Debian Linux 12.9 for v3.3.21.

**Comment by zero-top** [comment]
I found the cause of the problem. 

Firefox 128 does not support some APIs ( **`new Map().keys().toArray()`, `toArray` is not a function in firefox 128**). When I published it, I only tested Firefox 133+.🥲

https://github.com/zero-peak/ZeroOmega/blob/c6cca1e52825ce9c1d612fadd7d9862ebb8f32cf/omega-target-chromium-extension/src/module/proxy/proxy_impl.coffee#L45

**Comment by zero-top** [comment]
fixed in 3.3.22

https://addons.mozilla.org/en-US/firefox/addon/zeroomega/

**Comment by Uuzics** [comment]
> fixed in 3.3.22
> 
> https://addons.mozilla.org/en-US/firefox/addon/zeroomega/

Just updated to v3.3.22, can confirm it's fixed on Firefox 128. Thanks mate!
